version: ci-{build}
configuration: Release
clone_depth: 1
os: Visual Studio 2015
cache: reNX.Tests/bin/Release/data

branches:
    except:
        - coverity_scan

install:
    - git submodule update --init --recursive

before_build:
    - nuget restore

build:
    parallel: true
    verbosity: normal