language: csharp
os: linux
solution: reNX.sln
sudo: false

script:
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then xbuild /p:Configuration=Release reNX.sln; fi
    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mono ./packages/NUnit.Runners.*/tools/nunit-console.exe ./reNX.Tests/bin/Release/reNX.Tests.dll; fi

notifications:
    email: false
    irc:
        channels:
            - "irc.fyrechat.net#vana-commits"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}"

env:
    global:
        - secure: "hfAgHhUH1nWXsm7VsW0YNgvyb4HWwRdEnqBh6GByKNpaNvOi9yD0k8ZEO+jBtEvj4R9EAxm4oLVZu7SGYylO599X8YNMvVKI0hS1nyLBgSX9t6yfDv/j7WVnzaMc7zv8QRQ0kcwM7xSmwnhZX4PioSg8NE13H7rqgGtuPc4Qoyk="
        - secure: "dn4mQpIcqWZU6rQqBx9/Lz7yDyjcuJ4BVS6OrnluTjzt/lNSjf0zHYwScwL7X+qPtqCO6YaZk/ZdM4rRGXwC7bqExgbbfUmzvb9M0tRoZdgn/Q5RlwebMvcZL7oRCXgfQv9/PUPXKnjobqN7lYS8W6sra4QVC7vfeDlIkROroLY="

addons:
    coverity_scan:
        project:
            name: "angelsl/ms-reNX"
        notification_email: "$SEC_EMAIL"
        build_command: "xbuild /p:Configuration=Release reNX.sln"
        branch_pattern: coverity_scan
        