language: c
os: linux

install:
 - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
 - echo "deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main" | sudo tee -a /etc/apt/sources.list.d/mono-xamarin.list
 - sudo apt-get -qq update
 - sudo apt-get -qq install mono-devel

script:
 - xbuild /p:Configuration=Release reNX.csproj

notifications:
  email: false
  irc:
    channels:
     - "irc.fyrechat.net#vana-commits"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}"