language: csharp
os: linux
solution: reNX.csproj

notifications:
  email: false
  irc:
    channels:
     - "irc.fyrechat.net#vana-commits"
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} - %{author}): %{message}"